name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          mkdir -p public/badges public/lint
          echo undefined > public/badges/clint.score
          pip install anybadge cpplint
          sudo apt update
          sudo apt install -y bc
          git clone https://gitlab.esiea.fr/gauthier.heiss/c-file-scorer.git /tmp/c-file-scorer

      - name: Run lint scoring
        run: |
          /tmp/c-file-scorer/score.sh | tee public/lint/lint.txt
          tail -n 1 public/lint/lint.txt > public/badges/clint.score

      - name: Generate badge
        run: |
          anybadge --overwrite --label clint --value=$(cat public/badges/clint.score) \
            --file=public/badges/clint.svg 4=red 6=orange 8=yellow 10=green
          echo "Your score is: $(cat public/badges/clint.score)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public/
